name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test ./Gobie.UnitTests/Gobie.UnitTests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
    - name: Upload Verification Files on Fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: Acceptance Test Failure
        retention-days: 5
        path: |
          **/*.verified.txt
          **/*.received.txt
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        files: Gobie.UnitTests/coverage.opencover.xml      

defaults:
 run:
  working-directory: ./src/Gobie/
